2024 04.08/HengDaWeb/urls.py
from django.contrib import admin
from django.urls import path
from homeApp.views import home
from django.conf.urls import include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home,name='home'),
    path('aboutApp/',include('aboutApp.urls')),
    path('newsApp/',include('newsApp.urls')),
    path('serviceApp/',include('serviceApp.urls')),
    path('productApp/',include('productApp.urls')),
    path('scienceApp/',include('scienceApp.urls')),
    path('contactApp/',include('contactApp.urls')),
]

2024 04.08/aboutApp/urls.py
from django.urls import path
from . import views
app_name='aboutApp'
urlpatterns = [
    path('survey/',views.survey,name='survey'),
    path('honor/',views.honor,name='honor'),
]

2024 04.08/contactApp/urls.py
from django.urls import path
from . import views
app_name='contactApp'
urlpatterns = [
    path('contact/',views.contact,name='contact'),
    path('recruit/',views.recruit,name='recruit'),
]

2024 04.08/newsApp/urls.py
from django.urls import path
from . import views
app_name='newsApp'
urlpatterns = [
    path('company/',views.company,name='company'),
    path('industry/',views.industry,name='industry'),
    path('notice/',views.notice,name='notice'),
]

2024 04.08/productApp/urls.py
from django.urls import path
from . import views
app_name='productApp'
urlpatterns = [
    path('robot/',views.robot,name='robot'),
    path('monitoring/',views.monitoring,name='monitoring'),
    path('face/',views.face,name='face'),
]

2024 04.08/scienceApp/urls.py
from django.urls import path
from . import views
app_name='scienceApp'
urlpatterns = [
    path('science/',views.science,name='science'),
]

2024 04.08/serviceApp/urls.py
from django.urls import path
from . import views
app_name='serviceApp'
urlpatterns = [
    path('download/',views.download,name='download'),
    path('platform/',views.platform,name='platform'),
]

2024 04.08/aboutApp/models.py
from django.db import models

# Create your models here.

2024 04.08/contactApp/models.py
from django.db import models

# Create your models here.

2024 04.08/homeApp/models.py
from django.db import models

# Create your models here.

2024 04.08/newsApp/models.py
from django.db import models

# Create your models here.

2024 04.08/productApp/models.py
from django.db import models

# Create your models here.

2024 04.08/scienceApp/models.py
from django.db import models

# Create your models here.

2024 04.08/serviceApp/models.py
from django.db import models

# Create your models here.

2024 04.08/aboutApp/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
# Create your views here.
def survey(request):
    # html='<html><body>企业概况</body></html>'
    # return HttpResponse(html)
    return render(request,'survey.html')

def honor(request):
    # html='<html><body>荣誉资质</body></html>'
    # return HttpResponse(html)
    return render(request,'honor.html')

2024 04.08/contactApp/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
# Create your views here.
def contact(request):  # 欢迎咨询
    html='<html><body>欢迎咨询</body></html>'
    return HttpResponse(html)
def recruit(request):  # 加入恒达
    html='<html><body>加入恒达</body></html>'
    return HttpResponse(html)

2024 04.08/homeApp/views.py
from django.shortcuts import render
# from django.shortcuts import HttpResponse
# Create your views here.
def home(request):
    # html='<html><body>首页</body></html>'
    # return HttpResponse(html)
    return render(request,'index.html')

2024 04.08/newsApp/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
# Create your views here.
def company(request):
    html='<html><body>企业要闻</body></html>'
    return HttpResponse(html)
def industry(request):
    html='<html><body>行业新闻</body></html>'
    return HttpResponse(html)
def notice(request):
    html='<html><body>通知公告</body></html>'
    return HttpResponse(html)

2024 04.08/productApp/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
# Create your views here.
def  robot(request):    # 机器人
    html='<html><body>机器人</body></html>'
    return HttpResponse(html)
def monitoring(request): # 智能监控
    html='<html><body>智能监控</body></html>'
    return HttpResponse(html)
def face(request):    # 人脸识别
    html='<html><body>人脸识别</body></html>'
    return HttpResponse(html)

2024 04.08/scienceApp/views.py
from django.shortcuts import render
# from django.shortcuts import HttpResponse
# Create your views here.
def science(request):  # 科研基地
    # html='<html><body>科研基地</body></html>'
    # return HttpResponse(html)
    return render(request,'science.html')

2024 04.08/serviceApp/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
# Create your views here.
def download(request):
    html='<html><body>资料下载</body></html>'
    return HttpResponse(html)
def platform(request):
    html='<html><body>开放平台</body></html>'
    return HttpResponse(html)

2024 04.08/aboutApp/templates/honor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    6
</body>
</html>

2024 04.08/aboutApp/templates/survey.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    6
</body>
</html>

2024 04.08/homeApp/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>恒达科技</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
    <!-- bs3-navbar 导航条-->
    <nav class="navbar navbar-default" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">导航栏</span>
            </button>
        </div>
    
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav" style="width: 100%;">
                <li class="active"><a href="{% url 'home' %}">Home</a></li>
            <li class="dropdown nav-top">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'aboutApp:survey' %}">企业概况</a></li>
                    <li><a href="{% url 'aboutApp:honor' %}">荣誉资质</a></li>
                </ul>
            </li>

            <li class="dropdown nav-top">
                <a href="" class="dropdown-toggle" data-toggle="dropdown">新闻动态</a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'newsApp:company' %}">企业新闻</a></li>
                    <li><a href="{% url 'newsApp:industry' %}">行业新闻</a></li>
                    <li><a href="{% url 'newsApp:notice' %}">通知公告</a></li>
                </ul>
            </li>

            <li class="dropdown nav-top">
                <a href="" class="dropdown-toggle" data-toggle="dropdown">服务支持</a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'serviceApp:download' %}">资料下载</a></li>
                    <li><a href="{% url 'serviceApp:platform' %}">开放平台</a></li>
                </ul>
            </li>

            <li class="dropdown nav-top">
                <a href="" class="dropdown-toggle" data-toggle="dropdown">产品中心</a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'productApp:robot' %}">机器人</a></li>
                    <li><a href="{% url 'productApp:monitoring' %}">智能监控</a></li>
                    <li><a href="{% url 'productApp:face' %}">人脸识别</a></li>
                </ul>
            </li>
            
            <li class="dropdown nav-top">
                <a href="{% url 'scienceApp:science' %}">科研基地</a>
            </li>

            <li class="dropdown nav-top">
                <a href="" class="dropdown-toggle" data-toggle="dropdown">人才招聘</a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'contactApp:contact' %}">欢迎咨询</a></li>
                    <li><a href="{% url 'contactApp:recruit' %}">加入恒大</a></li>
                </ul>
            </li>
        </ul>

        </div><!-- /.navbar-collapse -->
    </nav>
    
</body>
</html>

2024 04.08/scienceApp/templates/science.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>恒达科技</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
    <!-- 页面头部 -->
    
    <div class="container top">

        <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <a>
                    
                    <img src="#" class="img-responsive" alt="Image" src="{% static 'img/logo.jpg' %}">
                    
                </a>
            </div>

            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <a class="phone ant">
                    <span class="glyphicon glyphicon-phone">电话：1145141919810&nbsp;&nbsp;</span>
                </a>
            </div>

            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <a class="mail ant">
                    <span class="glyphicon glyphicon-envelope">邮箱：1145141919810@6.com&nbsp;&nbsp;</span>             
                </a>
            </div>
        </div>
        
    </div>
    
</body>
</html>